export const productsCart = [
    {
        id: "1",
        name: "Camiseta Ramones",
        price_in_cents: 7042,
        size: 'G',
        descount_in_cents: 100,
        width_in_centimeters: 0,
        height_in_centimeters: 0,
        depth_in_centimeters: 0,
        codeColor: 'color2233',
        flavor: '',
        Weight_in_grams: 0,
        image_url: "https://storage.googleapis.com/xesque-dev/challenge-images/camiseta-04.jpg",
        description: "At sed adipisci ut ullam eaque. Et totam architecto eligendi. Eos sed veniam praesentium consequatur assumenda. Ut impedit quo a officiis est corrupti atque ea. Dignissimos voluptatem eaque nesciunt. Aut ipsam aut.",
        quantityPurchased: 1,
        quantity: 10
    },
    {
        id: "2",
        name: "Caneca Never settle",
        price_in_cents: 8652,
        size: '',
        descount_in_cents: 0,
        width_in_centimeters: 10,
        height_in_centimeters: 10,
        depth_in_centimeters: 10,
        codeColor: 'black',
        flavor: '',
        image_url: "https://storage.googleapis.com/xesque-dev/challenge-images/caneca-03.jpg",
        description: "Qui beatae provident eos vitae libero ut neque. Quisquam hic quas repellat natus illo ex. Enim debitis repudiandae veniam non quos dolores maxime. Inventore labore sint id. Labore repudiandae deserunt sed quia.",
        quantityPurchased: 1,
        quantity: 5
    },
]